(function(){'use strict';
const fighters=[{name:"Harry Fellows",division:"Heavyweight",rank:"Champion",record:"2-0-0"},{name:"Fin “D” Drakeley",division:"Heavyweight",rank:"#1",record:"4-0-0"},{name:"Fin “Gabz” Gabriel",division:"Heavyweight",rank:"#2",record:"3-0-1"},{name:"Noah Mcgeown",division:"Heavyweight",rank:"#3",record:"2-0-0"},{name:"Harry “Bart” Cartwright",division:"Heavyweight",rank:"#4",record:"2-0-1"},{name:"Archie “Burch” Bertram",division:"Heavyweight",rank:"#5",record:"1-0-1"},{name:"Ubayd Nayeem",division:"Heavyweight",rank:"#6",record:"0-0-1"},{name:"Max “MD” Drury",division:"Heavyweight",rank:"#7",record:"0-0-1"},{name:"Josh “Jabba” Jones",division:"Heavyweight",rank:"#8",record:"0-0-2"},{name:"Eddie Matthews",division:"Heavyweight",rank:"#9",record:"0-0-2"},{name:"Isaac “Deebs” Deeble",division:"Heavyweight",rank:"#10",record:"0-0-2"},{name:"Zach “Scouse” Horton",division:"Middleweight",rank:"Champion",record:"3-0-1"},{name:"Archie “Bald” Vickarage",division:"Middleweight",rank:"#1",record:"2-1-0"},{name:"Luke “Two Stroke” Tracey",division:"Middleweight",rank:"#2",record:"2-1-0"},{name:"Ethan “Whitt” Whittle",division:"Middleweight",rank:"#3",record:"0-1-1"},{name:"Zain “Muncher” Mohammed",division:"Middleweight",rank:"#4",record:"0-0-1"},{name:"Harry “HS” Sam",division:"Middleweight",rank:"#5",record:"0-0-2"},{name:"Azhari “AZ” Scrivens",division:"Middleweight",rank:"#6",record:"0-0-2"},{name:"Olly “Barris” Harris",division:"Lightweight",rank:"Champion",record:"4-1-0"},{name:"Callum Humphries",division:"Lightweight",rank:"#1",record:"2-0-2"},{name:"Fraser “Fraz” Evans",division:"Lightweight",rank:"#2",record:"2-1-1"},{name:"Greyson Hewitt",division:"Lightweight",rank:"#3",record:"1-0-1"},{name:"Elliot “Proper” Court",division:"Lightweight",rank:"#4",record:"1-0-1"},{name:"“Doctor” Alex Garner",division:"Lightweight",rank:"#5",record:"1-0-1"},{name:"Lucian “Loosh” Daves",division:"Lightweight",rank:"#6",record:"1-0-0"},{name:"Joe “Chan” Chandler",division:"Lightweight",rank:"#7",record:"0-0-1"},{name:"Leo Gibbs",division:"Lightweight",rank:"#8",record:"0-0-1"},{name:"Ashton “Rayman” Woodfield",division:"Lightweight",rank:"#9",record:"0-0-2"},{name:"Jake Badham",division:"Lightweight",rank:"#10",record:"0-0-2"}];
const powerRankings=["Harry Fellows","Greyson Hewitt","Fin “Gabz” Gabriel","Harry “Bart” Cartwright","Lucian “Loosh” Daves","Fin “D” Drakeley","Zach “Scouse” Horton","Callum Humphries","Olly “Barris” Harris","Noah Mcgeown","Archie “Burch” Bertram","Archie “Bald” Vickarage","Fraser “Fraz” Evans","Max “MD” Drury","Josh “Jabba” Jones"];
const pages=['home','stats','classes','power','heavy','middle','light','search','fighter','upcoming','fight-month','champions'];
const divisions={Heavyweight:'heavy',Middleweight:'middle',Lightweight:'light'};
const fighterMap=new Map(fighters.map(f=>[slug(f.name),f]));
function slug(s){return String(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function recordParts(r){const p=r.split('-').map(Number);return{wins:p[0]||0,losses:p[1]||0,draws:p[2]||0}}
function rankNumber(rank){const m=String(rank).match(/\d+/);return m?Number(m[0]):0}
function go(target){target=String(target||'').replace(/^#/,'');if(!target)return;if(location.hash.slice(1)===target){showPage(target)}else{location.hash=target}}
window.go=go;
function renderDivision(div){const target=document.getElementById(divisions[div]);if(!target)return;const list=fighters.filter(f=>f.division===div);const champ=list.find(f=>f.rank==='Champion');const ranked=list.filter(f=>f.rank!=='Champion').sort((a,b)=>rankNumber(a.rank)-rankNumber(b.rank));target.innerHTML='<div class="rank-card"><div class="rank-card-head"><h2>'+div.toUpperCase()+'</h2><p>Official rankings</p></div>'+(champ?'<a class="champ-row" href="#fighter/'+slug(champ.name)+'"><div class="champ-belt">🥊</div><div><div class="fighter-link">'+escapeHtml(champ.name)+'</div><div class="champ-tag">CURRENT CHAMPION</div></div><div class="record">'+champ.record+'</div></a>':'')+ranked.map((f,i)=>'<a class="rank-row" href="#fighter/'+slug(f.name)+'"><div class="rank-num">#'+(i+1)+'</div><div><div class="fighter-link">'+escapeHtml(f.name)+(i<2?'<span class="movement">↑</span>':'')+'</div></div><div class="record">'+f.record+'</div></a>').join('')+'</div>'}
function renderPower(){const box=document.getElementById('powerList');if(!box)return;box.innerHTML=powerRankings.map((name,i)=>{const f=fighterMap.get(slug(name));return '<a class="power-row" href="#fighter/'+slug(name)+'"><div class="power-number">#'+(i+1)+'</div><div class="fighter-link">'+escapeHtml(name)+'</div>'+(f?'<div class="record">'+f.division+' • '+f.record+'</div>':'<div></div>')+'</a>'}).join('')}
function renderSearch(q){const box=document.getElementById('searchResults');if(!box)return;const query=(q||'').trim().toLowerCase();if(!query){box.innerHTML='<div class="empty">Type a name to search every fighter.</div>';return}const matches=fighters.filter(f=>f.name.toLowerCase().includes(query));box.innerHTML=matches.length?matches.map(f=>'<a class="result" href="#fighter/'+slug(f.name)+'"><div><div class="result-name">'+escapeHtml(f.name)+'</div><div class="result-meta">'+(f.rank==='Champion'?f.division+' Champion':f.division+' '+f.rank)+' — '+f.record+'</div></div><strong style="color:var(--gold)">→</strong></a>').join(''):'<div class="empty">No fighters found.</div>'}
function renderStats(){const box=document.getElementById('statsGrid');if(!box)return;const cards=[['MOST WINS',[['Fin "D" Drakeley','4'],['Olly "Barris" Harris','4'],['Zach Horton','3']]],['BEST PROSPECT',[['Harry Fellows','C HW'],['Greyson Hewitt','#3 LW'],['Archie "Burch" Bertram','']]],['LONGEST WIN STREAK',[['Fin "D" Drakeley','4'],['Olly "Barris" Harris','4'],['Fin "Gabz" Gabriel','3']]],['MOST LOSSES',[['Jake Badham','2'],['Isaac "Deebs" Deeble','2'],['Ashton "Rayman" Woodfield','2']]],['CHAMPIONS',[['Olly "Barris" Harris','LW'],['Harry Fellows','HW'],['Zach "Scouse" Horton','MW']]]];box.innerHTML=cards.map(c=>'<article class="stat-card"><h3>'+c[0]+'</h3><ol>'+c[1].map((x,i)=>'<li><span class="pos">'+(i+1)+'</span><span>'+escapeHtml(x[0])+'</span><span class="value">'+escapeHtml(x[1])+'</span></li>').join('')+'</ol></article>').join('')}
function renderChampions(){const box=document.getElementById('championsGrid');if(!box)return;box.innerHTML=fighters.filter(f=>f.rank==='Champion').map(f=>'<a class="champion-card" href="#fighter/'+slug(f.name)+'"><div class="division">🥊 '+f.division.toUpperCase()+'</div><h2>'+escapeHtml(f.name)+'</h2><div class="record-big">'+f.record+'</div></a>').join('')}
function renderProfile(name){const f=fighterMap.get(name);const box=document.getElementById('fighterContent');if(!box)return;if(!f){box.innerHTML='<div class="panel" style="padding:28px"><h2>FIGHTER NOT FOUND</h2><p style="color:#999">Use Search Fighters to find a fighter.</p></div>';return}const r=recordParts(f.record);const isChamp=f.rank==='Champion';const fights={'Harry Fellows':[['W','Fin “Gabz” Gabriel'],['W','Harry “Bart” Cartwright']],'Fin “Gabz” Gabriel':[['L','Harry Fellows']],'Harry “Bart” Cartwright':[['L','Harry Fellows']]}[f.name]||[];const back=document.getElementById('fighterBack');if(back)back.href='#'+(divisions[f.division]||'search');box.innerHTML='<div class="profile"><article class="panel profile-main"><p class="eyebrow">'+(isChamp?'CHAMPION':'FIGHTER PROFILE')+'</p><h1 class="profile-name">'+escapeHtml(f.name)+'</h1><div class="profile-meta"><span class="tag">'+f.division+'</span><span class="tag '+(isChamp?'gold':'')+'">'+(isChamp?'CHAMPION':f.rank)+'</span><span class="tag">'+f.record+'</span></div><div class="fight-history"><h2 style="font-family:Impact,Haettenschweiler,Arial Narrow Bold,Arial,sans-serif;letter-spacing:.04em">FIGHT HISTORY</h2>'+(fights.length?fights.map(x=>'<div class="fight-item"><span class="win">'+x[0]+'</span><span>'+escapeHtml(x[1])+'</span><span class="record">'+f.record+'</span></div>').join(''):'<div class="empty">No fight history added yet.</div>')+'</div></article><aside class="panel profile-side"><p class="eyebrow">RECORD</p><div class="profile-stat"><span>Wins</span><span>'+r.wins+'</span></div><div class="profile-stat"><span>Losses</span><span>'+r.losses+'</span></div><div class="profile-stat"><span>Draws</span><span>'+r.draws+'</span></div><div class="profile-stat"><span>Division</span><span>'+f.division+'</span></div><div class="profile-stat"><span>Ranking</span><span>'+f.rank+'</span></div></aside></div>'}
function showPage(id){let base=id||'home';if(base.startsWith('fighter/')){renderProfile(base.slice(8));base='fighter'}if(!pages.includes(base))base='home';document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));const el=document.getElementById(base);if(el)el.classList.add('active');document.querySelectorAll('.bottom-nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+base||(['heavy','middle','light','power'].includes(base)&&a.getAttribute('href')==='#classes')));window.scrollTo(0,0)}
function route(){showPage(location.hash.replace(/^#/,'')||'home')}
function init(){Object.keys(divisions).forEach(renderDivision);renderPower();renderStats();renderChampions();renderSearch('');const input=document.getElementById('fighterSearch');if(input)input.addEventListener('input',e=>renderSearch(e.target.value));document.addEventListener('click',function(e){const a=e.target.closest('a[href^="#"]');if(!a)return;const href=a.getAttribute('href');if(!href||href==='#')return;e.preventDefault();go(href)});window.addEventListener('hashchange',route);route()}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',init)}else{init()}
})();

// App shell helpers
window.addEventListener('beforeinstallprompt', function(e){
  e.preventDefault();
  window.bartwrightsInstallPrompt = e;
});
window.addEventListener('appinstalled', function(){ window.bartwrightsInstallPrompt = null; });
